apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  host: {{ .Values.host | b64enc }}
  verify: {{ .Values.verify | b64enc }}
  username: {{ .Values.username | b64enc }}
  password: {{ .Values.password | b64enc }}